### ISSUE TITLE
Criar Limite de caracteres no campo input

### ISSUE THREAD

**Issue by viniciusgferreira** [lilian-rangel/Projeto-CRUD#1]
![image](https://user-images.githubusercontent.com/30271243/205387731-cdb6059f-dcde-49a7-9aa4-a0b4c78c0344.png)

**Comment by lilian-rangel** [comment]
Olá, Vinicius. 
Muito obrigada pela dica. Erro arrumado.

![maxlength](https://user-images.githubusercontent.com/105670314/207708653-c8ab5ea5-36ca-44c5-8887-bd8835fad0eb.jpg)
